### ISSUE TITLE
Rust does not have 'only one debugger'

### ISSUE THREAD

**Issue by romatthe** [open-dotnet/.github#26]
Hi, just wanted to point out that the organization profile README makes a statement that I feel is incorrect. It says "Did you know Rust only has one debugger?". This is not true.

Depending on how you look at things, Rust either has no official debugger, or many. You can debug Rust with GDB, LLDB, WinDBG and I believe even using the debugger in Visual Studio (whatever that thing is actually called) might also work if you compile Rust using an MSVC target. (in which case it should emit PDB debug info) I don't use Windows or Visual Studio so I can't really confirm that.

So rather than having its own debugger infrastructure, Rust just uses existing technology for native code like DWARF or PDB in the case of MSVC. The focus has been on getting Rust support into other projects like GDB and LLDB. Whenever you set up Rust using `rustup`, you get `rust-gdb` and `rust-lldb`, which are versions of both GDB and LLDB that have additional python scripts shipped with them for pretty-printing certain types of symbols (e.g. Rust enums).

**Comment by ghuntley** [comment]
Thanks for the correction, I am wrong and I need to find a better way to make the comparison/message that other languages have open tools but .NET remains under a walled garden. Any suggestions? Would love a PR.

**Comment by ghuntley** [comment]
Have made the appropriate changes thanks so much for helping with this @romatthe
