### ISSUE TITLE
Joining .NET Foundation

### ISSUE THREAD

**Issue by wieslawsoltes** [open-dotnet/.github#7]
Any plans to join the  .NET Foundation https://dotnetfoundation.org/member/become-a-member

**Comment by ghuntley** [comment]
> Any plans to join the .NET Foundation [dotnetfoundation.org/member/become-a-member](https://dotnetfoundation.org/member/become-a-member)

The .NET Foundation needs to resolve problems related to the articles of incorporation that give Microsoft veto over all decisions before joining the foundation would be appropriate but yes, the desire is to join the .NET Foundation and for the foundation to be also open and independent.

**Comment by ghuntley** [comment]
Started discussion over at https://github.com/dotnet-foundation/Home/discussions/74

**Comment by ghost** [comment]
How about join dotnet as Apache or CNCF as a member project?
Because we do not need to create a new Dedicated open source foundation?
